.TH "md___users_vadimpiven__development_berlekamp-zassenhaus_src__r_e_a_d_m_e" 3 "Сб 21 Сен 2019" "Version 1.0.0" "Berlekamb-Zassenhaus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md___users_vadimpiven__development_berlekamp-zassenhaus_src__r_e_a_d_m_e \- Использование 
Данный проект использует систему сборки \fCcmake\fP\&. Для компиляции проекта необходимо наличие установленных \fCmake\fP и \fCcmake\fP, а также компиляторов \fCgcc\fP и \fCg++\fP\&. Реализация полагается на наличие библиотеки \fCpthread\fP и её поддержки операционной системой\&. Для выполнения сборки или компиляции достаточно выполнить \fCmake rtest\fP для версии \fCRelease\fP или \fCmake dtest\fP для версии \fCDebug\fP, после чего выведется результат \fCdiff\fP сравнения результата выполнения программы при последнем запуске (\fCpoly\&.out\fP) с эталонным результатом (\fCpoly\&.gold\fP)\&. 
