.TH "/Users/vadimpiven/Development/berlekamp/Polynomial.cpp" 3 "Пт 4 Окт 2019" "Version 1.0.0" "irrpolygf2" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/Users/vadimpiven/Development/berlekamp/Polynomial.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'Polynomial\&.hpp'\fP
.br

.SH "Подробное описание"
.PP 

.PP
\fBАвтор\fP
.RS 4
Vadim Piven vadim@piven.tech 
.RE
.PP
\fBДата\fP
.RS 4
2019/09/22 @license Free use of this library is permitted under the guidelines and in accordance with the MIT License (MIT)\&. @url https://github.com/vadimpiven/irrpolygf2 
.RE
.PP

.SH "Автор"
.PP 
Автоматически создано Doxygen для irrpolygf2 из исходного текста\&.
